Update documentation
liip/pontsun pull request #9
Opened 2019-08-29 14:50 UTC by ragusa87

2019-10-10 09:24 UTC, Aerzas requested changes
Good idea to clean it up, there some obsoletes infos (not all coming from you proposal) which could be updated along the way probably.

2019-10-10 09:24 UTC, Aerzas commented on README.md
> +- Dnsseq configured to forward \*.test domains on localhost.
There may be a typo to "dnsseq".

2019-10-10 09:24 UTC, Aerzas commented on README.md
> +You can add the generated certificate `certificates/docker.rootCA.crt` to your browser authorities and trust related websites.
We generate certificates named `pontsun.rootCA.crt`, don't we ?

2019-10-10 09:24 UTC, Aerzas commented on README.md
> +. .env
I'm not sure this is a required step.

2019-10-10 09:24 UTC, Aerzas commented on README.md
> +- https://portainer.docker.test/#/home
Domain names are `*.ponstun.test`, aren't they ?

2019-10-10 09:24 UTC, Aerzas commented on docs/installation-for-mac.md
> +Dnsmasq will automatically forward any **\*.docker.test** domain to our
Same here, domain should be `pontsun.test`

2019-10-10 09:24 UTC, Aerzas commented on docs/installation-for-mac.md
> +echo 'address=/docker.test/127.0.0.1' > $(brew --prefix)/etc/dnsmasq.conf
Domain again

2019-10-17 12:56 UTC, OdyX commented on README.md
> +You can add the generated certificate `certificates/docker.rootCA.crt` to your browser authorities and trust related websites.
Nope. Not in `master`

2019-10-17 12:56 UTC, OdyX commented on README.md
> +- https://portainer.docker.test/#/home
Not in `master` as of now.

2019-10-17 12:58 UTC, OdyX commented
@Aerzas Rebased and split in 3 commits. Not everything is perfect, but the most obvious things are fixed.

2019-10-18 09:10 UTC, merged